// coach-data.js
//
// Static catalog for the simplified E.5 coach browser.

const CoachData = [
  {
    id: 'coach_meyer_luc',
    name: 'Luc Meyer',
    nationality: 'FR',
    title: 'CM',
    weeklyCost: 30,
    eloUnlock: 800,
    style: 'patient',
    background: 'Runs a community chess club and works well with beginners.',
    primaryThemes: ['fork'],
    bonusMoves: 1,
  },
  {
    id: 'coach_silva_ines',
    name: 'Ines Silva',
    nationality: 'PT',
    title: 'WCM',
    weeklyCost: 40,
    eloUnlock: 800,
    style: 'calm',
    background: 'Lisbon scholastic coach focused on pattern repetition and confidence building.',
    primaryThemes: ['mateIn1'],
    bonusMoves: 1,
  },
  {
    id: 'coach_kowalski_marek',
    name: 'Marek Kowalski',
    nationality: 'PL',
    title: 'FM',
    weeklyCost: 110,
    eloUnlock: 1200,
    style: 'sharp',
    background: 'Aggressive open specialist who teaches forcing lines and tactical conversion.',
    primaryThemes: ['sacrifice', 'sicilianDefense'],
    bonusMoves: 2,
  },
  {
    id: 'coach_haddad_nadia',
    name: 'Nadia Haddad',
    nationality: 'DZ',
    title: 'WFM',
    weeklyCost: 120,
    eloUnlock: 1250,
    style: 'methodical',
    background: 'Known for clean tactical teaching and relentless motif drilling.',
    primaryThemes: ['pin', 'skewer'],
    bonusMoves: 2,
  },
  {
    id: 'coach_petrova_elena',
    name: 'Elena Petrova',
    nationality: 'RU',
    title: 'IM',
    weeklyCost: 150,
    eloUnlock: 1300,
    style: 'strict',
    background: 'Former Moscow junior champion, now coaching ambitious improvers.',
    primaryThemes: ['ruyLopez', 'backRankMate'],
    bonusMoves: 2,
  },
  {
    id: 'coach_larsen_sofie',
    name: 'Sofie Larsen',
    nationality: 'DK',
    title: 'IM',
    weeklyCost: 145,
    eloUnlock: 1300,
    style: 'balanced',
    background: 'Copenhagen trainer with a reputation for practical, all-phase preparation.',
    primaryThemes: ['italianGame', 'mateIn2'],
    bonusMoves: 2,
  },
  {
    id: 'coach_popescu_andrei',
    name: 'Andrei Popescu',
    nationality: 'RO',
    title: 'FM',
    weeklyCost: 135,
    eloUnlock: 1300,
    style: 'pragmatic',
    background: 'Open-circuit coach who emphasizes practical decision-making over memorization.',
    primaryThemes: ['hangingPiece', 'trappedPiece'],
    bonusMoves: 2,
  },
  {
    id: 'coach_nguyen_minh',
    name: 'Minh Nguyen',
    nationality: 'VN',
    title: 'IM',
    weeklyCost: 155,
    eloUnlock: 1400,
    style: 'technical',
    background: 'Patient technician whose students improve fastest in endings and clean conversion.',
    primaryThemes: ['discoveredAttack', 'attackingF2F7'],
    bonusMoves: 2,
  },
  {
    id: 'coach_fischer_anna',
    name: 'Anna Fischer',
    nationality: 'DE',
    title: 'GM',
    weeklyCost: 390,
    eloUnlock: 1800,
    style: 'precise',
    background: 'Elite Bundesliga veteran offering broad, polished preparation across all phases.',
    primaryThemes: ['opening', 'middlegame', 'endgame', 'deflection'],
    bonusMoves: 3,
  },
  {
    id: 'coach_rinaldi_marco',
    name: 'Marco Rinaldi',
    nationality: 'IT',
    title: 'GM',
    weeklyCost: 520,
    eloUnlock: 2000,
    style: 'demanding',
    background: 'Ex-second in elite opens, feared for tactical prep and sharp opening files.',
    primaryThemes: ['attraction', 'fork', 'sacrifice', 'sicilianDefense'],
    bonusMoves: 3,
  },
];

if (typeof window !== 'undefined' && window.cl) {
  window.cl.coachData = CoachData;
}
